version: '3.8'

services:
  postgres-db:
    build:
      context: ./postgres-db
      dockerfile: Dockerfile
    env_file: 
      - ./postgres-db/.env
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./migrations:/app/migrations
      - ./data:/app/data
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 256M

volumes:
  postgres-data: